### PR TITLE
40 loginregisterhide

### PR DESCRIPTION
**Pull request by ryksyy**
Reworked navbar to use map so its easy to show/hide elements based on login status for example

added a logincontext class that can be used to pass logged in state to components

added a dropdown to navbar for vizualisations, TODO: components

also removed Home link from navbar, you get home now by clicking project name/logo

added a script using concurrent that starts both back and frontend by using npm run startDev in root of the project

### CODE REVIEW

**Comment by ryksyy** [comment]
after approving you can delete 40 and 49 branches

**Review by lassesuomela — CHANGES_REQUESTED** [review]
LogContext should be renamed to LoginContext or similar to prevent confusion.

Removing Home link from nav bar might also confuse users as they cant see it, so maybe add it back? idk.

**Review by lassesuomela — CHANGES_REQUESTED** [review]
const [ logState, setLogState ] = useState(false);
const log = useMemo(() => ({ logState, setLogState }), [logState, setLogState]);

Rename also those to match their actual uses. Something like isLoggedIn or similar

**Comment by ryksyy** [comment]
> const [ logState, setLogState ] = useState(false); const log = useMemo(() => ({ logState, setLogState }), [logState, setLogState]);
> 
> Rename also those to match their actual uses. Something like isLoggedIn or similar

these issues are now fixed

**Review by lassesuomela — APPROVED** [review]

**Pull request merged**
